### ISSUE TITLE
Error regarding TE and gene gtf files (?) when running mode 1

### ISSUE THREAD

**Issue by meoomen** [OliveiraDS-hub/ChimeraTE#16]
Hi! 

I'm trying to run ChimeraTE mode 1 on pig data. It seems to be running through the first steps just fine, but it runs into trouble after alignment. 

```
sys:1: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
Traceback (most recent call last):
  File "/home/ies/marlies.oomen/git_scripts/ChimeraTE_bam_input/chimTE_mode1.py", line 156, in <module>
    te_init(aln_dir, group, out_group)
  File "scripts/mode1_te_initiated.py", line 20, in te_init
    up_window = pd.read_table(str(aln_dir + '/genes_total_expressed.bed'), header=None, usecols=[0,1,2,3,4,5],names=['gene_id', 'start', 'end', 'id', 'dot', 'strand'])
  File "/home/ies/marlies.oomen/miniconda3/envs/chimeraTE/lib/python3.6/site-packages/pandas/io/parsers.py", line 767, in read_table
    return read_csv(**locals())
  File "/home/ies/marlies.oomen/miniconda3/envs/chimeraTE/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ies/marlies.oomen/miniconda3/envs/chimeraTE/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/ies/marlies.oomen/miniconda3/envs/chimeraTE/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/ies/marlies.oomen/miniconda3/envs/chimeraTE/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/ies/marlies.oomen/miniconda3/envs/chimeraTE/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/home/ies/marlies.oomen/git_scripts/ChimeraTE_bam_input/projects/test_chimera_defaults/rep1/alignment/genes_total_expressed.bed'
```

I would prefer running it already on my mapped bam files (using STAR), but I'm getting the same error using fastq or bam files as input (I used your answers on issue #6 to set up for running with bam input). Running it with the example data works just fine, so it doesn't seem to be an installation issue. 

Here are some example lines of my gene and TE gtfs: 

```
#!genome-build Sscrofa11.1
#!genome-version Sscrofa11.1
#!genome-date 2016-12
#!genome-build-accession NCBI:GCA_000003025.6
#!genebuild-last-updated 2017-06
1	ensembl	gene	3472	18696	.	-	.	gene_id "ENSSSCG00000037372"; gene_version "1"; gene_name "TBP"; gene_source "ensembl"; gene_biotype "protein_coding";
1	ensembl	transcript	3472	18546	.	-	.	gene_id "ENSSSCG00000037372"; gene_version "1"; transcript_id "ENSSSCT00000065539"; transcript_version "1"; gene_name "TBP"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "TBP-201"; transcript_source "ensembl"; transcript_biotype "protein_coding";
1	ensembl	exon	18493	18546	.	-	.	gene_id "ENSSSCG00000037372"; gene_version "1"; transcript_id "ENSSSCT00000065539"; transcript_version "1"; exon_number "1"; gene_name "TBP"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "TBP-201"; transcript_source "ensembl"; transcript_biotype "protein_coding"; exon_id "ENSSSCE00000190268"; exon_version "2";
1	ensembl	CDS	18493	18546	.	-	0	gene_id "ENSSSCG00000037372"; gene_version "1"; transcript_id "ENSSSCT00000065539"; transcript_version "1"; exon_number "1"; gene_name "TBP"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "TBP-201"; transcript_source "ensembl"; transcript_biotype "protein_coding"; protein_id "ENSSSCP00000053834"; protein_version "1";
1	ensembl	exon	14814	15217	.	-	.	gene_id "ENSSSCG00000037372"; gene_version "1"; transcript_id "ENSSSCT00000065539"; transcript_version "1"; exon_number "2"; gene_name "TBP"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "TBP-201"; transcript_source "ensembl"; transcript_biotype "protein_coding"; exon_id "ENSSSCE00000293218"; exon_version "1";

```

```
1	DAsusScro11.1.nrph	TE	641	712	.	-	.	AmmLer-1.137
1	DAsusScro11.1.nrph	TE	1256	1322	.	-	.	AmmLer-1.137
1	DAsusScro11.1.nrph	TE	1644	1785	.	+	.	L2b_3end
1	DAsusScro11.1.nrph	TE	3973	4144	.	-	.	MIRb
1	DAsusScro11.1.nrph	TE	4954	5141	.	-	.	L1M5_orf2
```

Any help/insight on what could be causing this error would be appreciated!

-Marlies

**Comment by OliveiraDS-hub** [comment]
Dear @meoomen, sorry for the delayed response.

Let's solve the issue to run with fastq data, then we check if any error persists with the bam files.

First of all, go the your project's folder, then tmp, and send the first lines of the files "gtf_file.gtf" and "gene_coord.bed".

Please, go also to the folder of your first replicate, then alignment, and send the first lines of the file "genes_expressed_IDs.lst" (if it exists). This file is created just after cufflinks analysis, and if you have something wrong with cufflinks then you might not have your expressed genes list.

I'll be waiting your response, thank you.
